package com.ohio.provider;

public class FieldsProvider {
	/* Fields to be used in Json creation*/
	public static String 
	   
	    SAK_PROV,
	    ID_PROVIDER_MCD,
	    CDE_COUNTY,
	    IND_OUT_STATE,
	    DTE_RECEIVED,
	    DTE_CYCLE,Prov_fname,Prov_lname,ADR_MAIL_STRT1,ADR_MAIL_STRT2,ADR_MAIL_CITY,ADR_MAIL_ZIP,ADR_MAIL_ZIP_4,ADR2,ADR_MAIL_STATE,
	    ID_CLERK,NUM_TAX_ID,NUM_PROV_SSN,ID_PROVIDER_NPI,CDE_PROV_ID_TYPE,IND_NPI_VERIFY,ID_FACILITY,ID_ICDS_PROV_CONTRACT,DERIVED,NA,DERIVED1,DTE_PR_ID_EFF,
	    DTE_PR_ID_END,IND_HEALTHCARE,DERIVED2,DERIVED3,NA1,NA2,NA3,DTE_ELECTRONIC_SIGNATURE,NA4,NA5,NA6,TXT_ACA_PAYMENT_CONFIRM,AMT_ACA_FEE,NA9,NA10,NA11,NA7,NA8,
	    ID_PROVIDER_VAL1,ID_PROVIDER_VAL2,CDE_PROV_TYPE,CDE_ORGANIZ,CDE_LIC_TYPE,NUM_PROV_LIC,DTE_EFFECTIVE,DTE_EFFECTIVE1,DTE_END,DTE_EFF_MCD_AGREEMENT,DTE_END_MCD_AGREEMENT,
	    DERIVED4,NUM_DEA,NUM_PHONE,NUM_PHONE_INT,CDE_PROV_PGM,NUM_LONGITUDE,NUM_LATITUDE,IND_TAX_ID_TYPE,DERIVED5,ADR2_MAIL_STRT1,ADR2_MAIL_STRT2,ADR2_MAIL_CITY,ADR2_MAIL_ZIP,ADR2_MAIL_STATE,
	    ADR3_MAIL_STRT1,ADR3_MAIL_STRT2,ADR3_MAIL_CITY,ADR3_MAIL_ZIP,ADR3_MAIL_STATE,DTE_EFFECTIVE2,ADR_EMAIL,NUM_PHONE1,
	    ADR4_MAIL_STRT1,ADR4_MAIL_STRT2,ADR4_MAIL_CITY,ADR4_MAIL_ZIP,ADR4_MAIL_STATE,NUM_PHONE2,Add5,Add6,DTE_EFFECTIVE3,contract1,contract2,contract3,special1,special2,special3,ProvTypeSpeciality;

	
	/*String for storing DB Results of Claims visit information*/
	public static String dbAccount, dbProv_lname,dbProv_fname,dbADR_MAIL_STRT1,dbADR_MAIL_STRT2,dbADR_MAIL_CITY,dbADR_MAIL_STATE,dbADR_MAIL_ZIP,dbNUM_PHONE,dbADR_EMAIL,dbID_PROVIDER_MCD,dbprovider_name,db_Agency_Account , dbProvider_Speciality , dbAppUserEmail , dbAppUserPassword ,dbErrorCode,
	dbinserttimestmp;


	
	
	
	
	
	
}
