package com.interop.sql;

public class AppUserSQL {

    public static String GET_INBOX_APP_USERS = "SELECT * FROM INBOX.APP_USERS WHERE USERNAME LIKE '%s'";

    public static String GET_APP_USERS_CM = "SELECT AUTH.AUTH_REF_NUMBER, AU.*, AUC.* FROM STX.APP_USERS AU JOIN STX.APP_USERS_CLI AUC \n" +
            "ON AU.USER_ID = AUC.USER_ID \n" +
            "JOIN STX.AUTHORIZATIONS auth \n" +
            "ON AUTH.CASE_MANAGER_E_MAIL = AU.USERNAME\n" +
            "WHERE ROWNUM  = '1' AND au.ACCOUNT = '9999' AND DESCRIPTION LIKE 'CASE MANAGER' AND AUC.ACCOUNT = '%s'";

    public static String GET_STX_APP_USER = "SELECT ACCOUNT, USERNAME, PASSWORD, DATA_SCOPE_ID, ACCOUNT_STATUS, USER_TYPE_ID,USER_ID, DELETED, USER_F_NAME, USER_L_NAME FROM STX.APP_USERS WHERE USERNAME = '%s'";

    public static String GET_STX_APP_USER_ACTIVE = "SELECT ACCOUNT, USERNAME, PASSWORD, DATA_SCOPE_ID, ACCOUNT_STATUS, USER_TYPE_ID,USER_ID, USER_F_NAME, USER_L_NAME, DELETED FROM STX.APP_USERS WHERE USERNAME = '%s' AND DELETED IS null";

    public static  String GET_STX_APP_USERS_CLI = "SELECT AUC.ACCOUNT,AUC.USER_ID, AUC.LOC, AUC.USERNAME, AUC.BEG_DATE, AUC.END_DATE FROM STX.APP_USERS au INNER JOIN STX.APP_USERS_CLI auc \n" +
            "ON AU.USER_ID = AUC.USER_ID\n" +
            "WHERE au.USERNAME LIKE '%s'";

    public static String GET_DELETED_CM = "SELECT * FROM STX.APP_USERS WHERE  DELETED IS NOT NULL AND DESCRIPTION LIKE 'CASE MANAGER' AND ACCOUNT = '9999'";

    public static String GET_USERNAME_IS_NOT_CM = "SELECT * FROM STX.APP_USERS WHERE DESCRIPTION NOT LIKE 'CASE_MANAGER' AND ACCOUNT = '9999'";

    public static String GET_CLIENT_MEDICAID_ID = "SELECT DISTINCT ai.PROVIDER_ID, cs.MEDICAID_ID FROM STX.CLIENTS c INNER JOIN STX.CLIENTS_SUPP cs \n" +
            "ON c.CLIENTKEY = cs.CLIENTKEY\n" +
            "INNER JOIN stx.ACCOUNTS_INTERFACES ai \n" +
            "ON ai.ACCOUNT = c.ACCOUNT\n" +
            "WHERE cs.MEDICAID_ID IS NOT NULL AND c.ACCOUNT = '%s'";

    public static String GET_STX_APP_USER_BY_USERID = "SELECT ACCOUNT, USERNAME, PASSWORD, DATA_SCOPE_ID, ACCOUNT_STATUS, USER_TYPE_ID,USER_ID, DELETED, USER_F_NAME, USER_L_NAME FROM STX.APP_USERS WHERE USER_ID = '%s'";

}
